name: mgread_ohos_media
description: MgRead's native OHOS AVPlayer host for audio and video playback.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ohos:
        package: com.mgread.mgread_ohos_media
        pluginClass: MgReadOhosMediaPlugin
